spring.application.name=bulletin-board
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/bulletinDB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=123


# Диалект для PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Автоматическое создание и обновление таблиц
spring.jpa.hibernate.ddl-auto=update

# Показывать SQL-запросы в консоли
spring.jpa.show-sql=true

# Форматировать SQL-запросы красиво
spring.jpa.properties.hibernate.format_sql=true

logging.level.root=INFO
logging.level.com.boardmaster=DEBUG

logging.level.org.hibernate.orm.jdbc.bind=TRACE